--enable-features=AcceleratedVideoDecodeLinuxGL,VaapiVideoDecoder,VaapiVideoDecodeLinuxGL,VaapiIgnoreDriverChecks,UseOzonePlatform,TouchpadOverscrollHistoryNavigation,WebRTCPipeWireCapturer
--disable-features=UseChromeOSDirectVideoDecoder
--ozone-platform=wayland
--enable-wayland-ime
--wayland-text-input-version=3
# --gtk-version=4
--proxy-auto-detect
--enable-accelerated-video-decode
--enable-logging 
--v=1
